@startuml provingDelegation

!include "skin.iwsd"

box "Prover" 
	participant "P2ABCEngine\nJava User Service" as p2abce #F18CA9
    participant "IoT device" as iot #9ABFD6
end box

participant Verifier #8CD1B8




iot -> Verifier : requestPresentationPolicy
note left #cdffda
    IoT device starts the
    proving protocol with
    the Verifier
end note

iot <- Verifier : presentationPolicyAlternatives.xml

|||

p2abce <- iot : [REST/CoAP/RPC/...]\nProving(presentationPolicyAlternatives.xml)
note right #bee6ff : IoT device delegates to P2ABCE\nserver the parsing of XML

p2abce --> iot : APDU Command
p2abce <-- iot : APDU Response
note right #FFEDB9 : Server requests IoT smart card to\nperform cryptographic operations


p2abce <--> iot : ...

p2abce -> iot : presentationToken.xml
note right #bee6ff : Server answers with the\nP2ABCE response XML

|||

iot -> Verifier : Proof to Verifier:\npresentationToken.xml
note left #cdffda
    IoT device resumes the
    communication with the Verifier
end note

@enduml