@startuml provingDelegation

!include "skin.iwsd"

box "Prover" 
	participant "P2ABCEngine\nJava User Service" as p2abce
    participant "IoT device" as iot
end box

participant Verifier

iot -> Verifier : requestPresentationPolicy
note left
    IoT device starts the
    proving protocol with
    the Verifier
end note

iot <- Verifier : presentationPolicyAlternatives.xml

|||

p2abce <- iot : [REST/CoAP/RPC/...]\nProving(presentationPolicyAlternatives.xml)
note right : IoT device delegates to P2ABCE\nserver the parsing of XML

p2abce --> iot : APDU Command
p2abce <-- iot : APDU Response
note right : Server requests IoT smart card to\nperform cryptographic operations


p2abce <--> iot : ...

p2abce -> iot : presentationToken.xml
note right : Server answers with the\nP2ABCE response XML

|||

iot -> Verifier : Proof to Verifier:\npresentationToken.xml
note left : IoT device resumes the\ncommunication with the Verifier

@enduml